namespace Maple2.File.Parser.Enum;

public enum ExpType {
    none = 0,
    telescope = 3,
    rareChest = 4,
    rareChestFirst = 5,
    normalChest = 6,
    dungeonBoss = 8,
}

public enum AdventureExpType {
    none,
    Exp_MapCommon,
    Exp_MapHidden,
    Exp_TaxiStation,
    Exp_Telescope,
    Exp_RareChest,
    Exp_RareChestFirst,
    Exp_NormalChest,
    Exp_DropItem,
    Exp_MusicMasteryLv1,
    Exp_MusicMasteryLv2,
    Exp_MusicMasteryLv3,
    Exp_MusicMasteryLv4,
    Exp_Arcade,
    Exp_Fishing,
    Exp_Rest,
    Exp_Quest,
    Exp_QuestETC,
    Exp_PvpBloodMineRank1,
    Exp_PvpBloodMineRank2,
    Exp_PvpBloodMineRank3,
    Exp_PvpBloodMineRankOther,
    Exp_PvpRedDuelWin,
    Exp_PvpRedDuelLose,
    Exp_PvpBtiTeamWin,
    Exp_PvpBtiTeamLose,
    Exp_PvpRankDuelWin,
    Exp_PvpRankDuelLose,
    Exp_Gathering,
    Exp_Manufacturing,
    Exp_MiniGame,
    Exp_UserMiniGame,
    Exp_UserMiniGameExtra,
    Exp_Mission,
    Exp_DungeonRelative,
    Exp_GuildUserExp,
    Exp_DailyGuildQuest,
    Exp_WeeklyGuildQuest,
    Exp_PetTaming,
    Exp_DailyMission,
    Exp_DailyMissionLevelUp,
    Exp_mapleSurvival,
    Exp_DarkStream,
    Exp_DungeonClear,
    Exp_KillMonster,
    Exp_KillMonsterElite,
    Exp_KillMonsterBoss,
    Exp_Construct,
    Exp_EpicQuest,
    Exp_RandomDungeonBonus,
    Exp_DungeonBoss,
}
